# Generated by Django 5.0.2 on 2024-03-04 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_ticket_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='title',
        ),
    ]
