# Generated by Django 5.0.2 on 2024-03-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_remove_ticket_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
